### ISSUE TITLE
Cannot use with @vue/cli v3

### ISSUE THREAD

**Issue by tommed** [malayvuong/vrcode#2]
**Describe the bug**
Unable to use this component,

```js
// extract from main.js
import Vue from 'vue'
//... 

import vrcode from '@ispa.io/vrcode'
Vue.component('vrcode', vrcode);

```

**To Reproduce**
1. `yarn add "@ispa.io/vrcode"`
2. Add code to main.js (see above)
3. `yarn serve`

**Expected behavior**
To run without any errors

**Output from yarn serve**

```
ERROR  Failed to compile with 2 errors                                                                                                        12:50:18
These dependencies were not found:

* qr.js/lib/ErrorCorrectLevel in ./node_modules/@ispa.io/vrcode/src/vue-qrcode.js
* qr.js/lib/QRCode in ./node_modules/@ispa.io/vrcode/src/vue-qrcode.js

To install them, you can run: npm install --save qr.js/lib/ErrorCorrectLevel qr.js/lib/QRCode
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro on Microsoft Surfacebook
 - Browser N/A issue happening in `yarn serve`

**Comment by malayvuong** [comment]
**Hello Tommed,**
Thanks for your issue. This is the first time i wrote a package so maybe something will be wrong.

The `qr.js` not available now on yarn, I had checked.
So now, you can install it by run this cmd:
```
npm i qr.js
```
Next version I'll remove yarn install / or upload `qr.js` libs into yarn so you can use it easily.

If you have any suggestions, please feel free to reply this issue.
